spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5